<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.1 (Python 3.8.5 on win32)" generated="20200723 16:30:21.223" rpa="false">
<suite id="s1" name="Qifi" source="C:\Users\anchisatea\Documents\Robot ws\qifi.robot">
<test id="s1-t1" name="ค้นหา anchisa ใน Google ผ่าน Chrome">
<kw name="เปิดโครมขึ้นมา">
<kw name="Open Browser" library="SeleniumLibrary">
<doc>Opens a new browser instance to the optional ``url``.</doc>
<arguments>
<arg>http://google.co.th</arg>
<arg>chrome</arg>
</arguments>
<msg timestamp="20200723 16:30:21.795" level="INFO">Opening browser 'chrome' to base url 'http://google.co.th'.</msg>
<kw name="Capture Page Screenshot" library="SeleniumLibrary">
<doc>Takes a screenshot of the current page and embeds it into a log file.</doc>
<msg timestamp="20200723 16:30:21.805" level="INFO">Cannot capture screenshot because no browser is open.</msg>
<status status="PASS" starttime="20200723 16:30:21.804" endtime="20200723 16:30:21.805"></status>
</kw>
<msg timestamp="20200723 16:30:21.819" level="FAIL">WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
</msg>
<status status="FAIL" starttime="20200723 16:30:21.794" endtime="20200723 16:30:21.820"></status>
</kw>
<status status="FAIL" starttime="20200723 16:30:21.793" endtime="20200723 16:30:21.820"></status>
</kw>
<status status="FAIL" starttime="20200723 16:30:21.789" endtime="20200723 16:30:21.822" critical="yes">WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
</status>
</test>
<status status="FAIL" starttime="20200723 16:30:21.230" endtime="20200723 16:30:21.827"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Qifi">Qifi</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
